# Generated by Django 3.1.6 on 2021-06-23 07:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.genereate_code, max_length=10, unique=True),
        ),
    ]
